
version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80" # Maps port 8080 on the host to port 80 in the container
    volumes:
      - ./nginx/html:/usr/share/nginx/html # Mount local HTML files to NGINX
      - ./nginx/conf.d:/etc/nginx/conf.d  # Custom NGINX configuration
    depends_on:
      - db  # Ensures MySQL starts before NGINX

  db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306" # Maps MySQL port
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql # Persistent storage for database

volumes:
  db_data:
